name: iOS Build Cache Experimentation

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Archive iOS
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      # Install and cache npm deps
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies
        run: npm ci

      # ✅ Pre-bundle React Native JS (speeds up archive)
      - name: Pre-bundle React Native JS
        run: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios/assets

      # Optional cache of bundle outputs
      - name: Cache JS Bundle
        uses: actions/cache@v4
        with:
          path: |
            ios/main.jsbundle
            ios/assets
          key: jsbundle-${{ hashFiles('**/*.js', 'package-lock.json') }}
          restore-keys: jsbundle-

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: pods-static

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install

      # ✅ DerivedData cache for native build reuse
      - name: Cache DerivedData (Xcode)
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.ref_name }}
          restore-keys: |
            xcode-cache-deriveddata-${{ github.workflow }}-
          restore-mtime-targets: |
            DemoApp/**/*

      # ✅ Archive app (uses pre-bundled JS + DerivedData cache)
      - name: Archive iOS App
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app
          cd ios
          mkdir -p build
          xcodebuild \
            -workspace DemoApp.xcworkspace \
            -scheme DemoApp \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/DemoApp.xcarchive \
            archive